// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyl-No3L2LDUmavlkKCjVWMZJQZKC8m0E',
    appId: '1:150640323935:web:936b67426dcb94bc6d5aea',
    messagingSenderId: '150640323935',
    projectId: 'vtr-notificacoes',
    authDomain: 'vtr-notificacoes.firebaseapp.com',
    databaseURL: 'https://vtr-notificacoes-default-rtdb.firebaseio.com',
    storageBucket: 'vtr-notificacoes.appspot.com',
    measurementId: 'G-MB5M0V29ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0aeXTeBl2pcX7vJjouVfKqC6_B-GGulM',
    appId: '1:150640323935:android:6eb82d7fc36fcd496d5aea',
    messagingSenderId: '150640323935',
    projectId: 'vtr-notificacoes',
    databaseURL: 'https://vtr-notificacoes-default-rtdb.firebaseio.com',
    storageBucket: 'vtr-notificacoes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2L7cc8mXm1hhnMbNM4rI8g9Wp_4NSrzQ',
    appId: '1:150640323935:ios:7f5dfcb95aed42e36d5aea',
    messagingSenderId: '150640323935',
    projectId: 'vtr-notificacoes',
    databaseURL: 'https://vtr-notificacoes-default-rtdb.firebaseio.com',
    storageBucket: 'vtr-notificacoes.appspot.com',
    iosBundleId: 'com.example.appVtr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2L7cc8mXm1hhnMbNM4rI8g9Wp_4NSrzQ',
    appId: '1:150640323935:ios:7f5dfcb95aed42e36d5aea',
    messagingSenderId: '150640323935',
    projectId: 'vtr-notificacoes',
    databaseURL: 'https://vtr-notificacoes-default-rtdb.firebaseio.com',
    storageBucket: 'vtr-notificacoes.appspot.com',
    iosBundleId: 'com.example.appVtr',
  );
}
